AllCops:
  TargetRubyVersion: 2.3

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

